### ISSUE TITLE
envdir setup is not easily greppable / envprint utility?

### ISSUE THREAD

**Issue by blueyed** [jezdez/envdir#17]
I am considering using envdir for a Django project, but get the impression that it may become more difficult to grep / search for settings and their values, given that they are split into filename and file content.

For example, you cannot just grep your settings / project folder anymore for DEBUG, EMAIL_ etc, without having to also grep (and then look into) the output of `find`.

Given that I am also looking into django-configurations, because it allows to have local, production and staging settings in a single file, this feels uncomfortable.

OTOH, envdir makes it easier already to have environment settings in a central location (`envs/{local,prod,...}`), which are scattered around otherwise (virtualenv's postactivate, wsgi server setting files, ...).

Just wanted to leave this as feedback - maybe there's an approach to make it easier to work with it?

Maybe a script / option could be provided, which only displays settings from a specific env dir in the form of `NAME=VALUE`.
Or when invoked in a directory with subdirs, would display it like grep as in:

```
$ envprint ./envs
prod: DEBUG=False
prod: FOO=1
local: DEBUG=True

$ envprint ./envs/local
DEBUG=True
```

**Comment by AlJohri** [comment]
@blueyed this works too:

```
➜   myproj [master] ⚡ tail envs/local/*
==> envs/local/DATABASE_URL <==
postgres://postgres@localhost:5432/election2016

==> envs/local/DEBUG <==
true

==> envs/local/SECRET_KEY <==
poop

==> envs/local/STAGE <==
dev
```
