### ISSUE TITLE
env file?

### ISSUE THREAD

**Issue by AlJohri** [jezdez/envdir#49]
hi @jezdez, this may be completely out of scope as the project is literally named env**dir**, but I was wondering if its possible to provide a single file with all of the variables for each environment. so like:

```
prod
  - .env
dev
  - .env
```

this is mainly because I run programs both locally and with docker and docker allows me to specify a `--env` argument with a single file of environment variables. this way I can use the same file of environment variables for locally running a program and docker

thanks!

**Comment by blueyed** [comment]
Interesting idea.
As a workaround you could use some build tool (e.g. make) to generate an env-file from an envdir or the other way around.

**Comment by jezdez** [comment]
This is definitely out of scope of the tool's main paradigm, as you correctly mentioned. Maybe we could add a cookbook section to the docs with a script that does the transformation from an envdir to enfile, e.g. `envdir2file`? Closing for now..

**Comment by AlJohri** [comment]
thanks @blueyed, that's what I ended up doing

posting this here for the future:

The snippets below accomplished what I needed.

Load `envs/local` or `.env` into current shell:
```
if [ -d "envs/local" ]; then
    echo "sourcing envs/local directory..."
    for f in envs/local/*; do eval $(echo export $(basename $f)=$(cat $f)); done
elif [ -f ".env" ]; then
    echo "sourcing .env file..."
    export $(cat .env | grep -v "^#" | xargs)
fi
```
Replacing `eval` with `echo` in the for loop can help create a real env file if one likes. Sourcing it into the current shell worked well enough for me.

docker-compose using external environment variables instead of an `env-file` file
```
version: '2'
services:
  myservice:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
```
https://docs.docker.com/compose/environment-variables/#/substituting-environment-variables-in-compose-files

usage if env variables are loaded in current shell: `docker-compose up myservice`
usage using envdir: `envdir envs/local docker-compose up myservice`

**Comment by AlJohri** [comment]
I'm running into an issue where I have multiple service each with their own `envs` directory and corresponding `docker-compose` files. I want to create a single docker-compose file that runs that services together for testing locally. The easiest way to do that is by providing the [`env_file` option](https://docs.docker.com/compose/compose-file/#env_file) for each service that builds an env_file based off of its `envs` folder. Trying to figure out some way to create a `symlink` style file that represents a `.env` version of the entire `envs/local` folder. Any ideas on how to do something like that? I thought it might have something to do with named pipes.

**Comment by blueyed** [comment]
@AlJohri 
You can use a Makefile to generate envfiles from envdirs:
```make
build/envfile.%: %/* %/
	@echo "Generating envfile $@"
	@for i in $^; do \
	  test -f "$$i" || continue; \
	  name=$$(basename $$i); \
	  echo "$$name=$$(cat $$i)" >> $@; \
	done > "$@"
```

`make build/envfile.prod` will build that from `envdir.prod` then.

**Comment by blueyed** [comment]
Oh well, I suggested that already..

Anyway, it seems what you would like to use?!

**Comment by AlJohri** [comment]
haha thanks! that looks good, I'll have to try that. not as great at the bashfu just yet :)
