### ISSUE TITLE
symlinks don't work

### ISSUE THREAD

**Issue by AlJohri** [jezdez/envdir#51]
I would like to share some environment variables between stages and the easiest way to do that seems to be to symlink from my `local` (i.e. default) environment into my `production` and `staging` environments. In the example below, I would like to share the `DJANGO_SETTINGS_MODULE` and `PYTHONPATH` variables between all stages.

Currently envdir doesn't follow symlinks so the variables will be missing if symlinked.

This seems like a feature that's just enough in scope @jezdez :) Let me know if you want me to give a shot at a PR!

```
➜   envs [master] ⚡ tree
.
├── local
│   ├── DATABASE_URL
│   ├── DEBUG
│   ├── DJANGO_SETTINGS_MODULE
│   ├── PYTHONPATH
│   └── STAGE
├── production
│   ├── DATABASE_URL
│   ├── DEBUG
│   ├── DJANGO_SETTINGS_MODULE
│   ├── PYTHONPATH
│   └── STAGE
└── staging
    ├── DATABASE_URL
    ├── DEBUG
    ├── DJANGO_SETTINGS_MODULE
    ├── PYTHONPATH
    └── STAGE
```

Thanks!

cc @blueyed

**Comment by jezdez** [comment]
Sounds like a bug to me, to be honest

**Comment by blueyed** [comment]
Thanks, @ticosax!
