### ISSUE TITLE
overriding environment variables

### ISSUE THREAD

**Issue by AlJohri** [jezdez/envdir#55]
To debug errors, I'm often running code locally using `envs/prod` to test something and have to override `DEBUG` to `true`.

It would be helpful to be able to do something like this:
```
DEBUG=true envdir envs/prod make runserver
```

to easily override a single variable. Not quite sure on the syntax or implementation details though. 

Is there any interest in something like this? Do most people just create a separate environment like `prod-debug` or `prod-local`?

**Comment by AlJohri** [comment]
duplicate of #12 ?

**Comment by blueyed** [comment]
Yes.

Use the `env` method I posted there.
