### ISSUE TITLE
Missing .pyz for 0.7.0

### ISSUE THREAD

**Issue by rouge8** [jezdez/envdir#57]
The 0.7.0 release is missing a `.pyz` download

**Comment by blueyed** [comment]
Can you provide a PR, please?

**Comment by rouge8** [comment]
No? This is something that a maintainer will have to do [on the releases page](https://github.com/jezdez/envdir/releases). I created one and provided a sha1sum [on our fork](https://github.com/GoodRx/envdir/releases/tag/0.7) if you want to use that.

**Comment by jezdez** [comment]
@rouge8 I'll add one. Thanks for the reminder.

**Comment by jezdez** [comment]
Uploaded, https://github.com/jezdez/envdir/releases/tag/0.7
