### ISSUE TITLE
pypi version 0.7 outdated, no release in over 3 years

### ISSUE THREAD

**Issue by willharris** [jezdez/envdir#66]
Would be nice to have an up-to-date release in pypi, so people don't waste time with bugs that have already been fixed since 2 years.

**Comment by jezdez** [comment]
You know what? I would have replied "Sure!" but the condescending way you wrote this make me really write: "Nope."

I suggest to stop using envdir instead.

**Comment by willharris** [comment]
Wow dude. Just... wow.

If my irritation at having wasted an hour of my life debugging a problem that had already been fixed well over a year ago, and yet for some reason not released, rubbed you the wrong way, well you have my sincere condolences on your incredibly thin skin.

Perhaps you should rethink your career in open source.

**Comment by jezdez** [comment]
It's okay that you don't get it, but I'm sad that you think that having tough skin is a requirement for working in the Open Source community. Wouldn't it be simpler to just write "please" and "could you"? Or god forbid "how can I help?" It doesn't take much you know?

Fact is I don't owe you my time doing a release, you decided to use a software I wrote for free, with no strings attached. And all I want is for once be asked nicely to spend less time with my family to do this volunteer work. That's not too much to ask in my opinion.

Good luck.

**Comment by willharris** [comment]
Man I feel like I'm in couples' therapy.

I do get it, and I'm extremely grateful to people like you who put stuff out there. So - thank you for your hard work.

Fact is though, when you put out something and release it on PyPI such that it becomes the de-facto standard in Python-land, other devs will have certain expectations. If you don't want to maintain it anymore, maybe you could just say so, and someone else can take over?

As to thin skin: yes, I think you're overreacting (thanks for tweeting about this too btw). Objectively, my bug report is a statement of fact - devs (probably not just me) are wasting time simply due to the PyPI version not being maintained, and not being indicated as unmaintained. That you took it as condescending is unfortunate, as I did not intend it to be such. Perhaps I should have added a 😊.

So again, thanks for your time, and sorry you found the wording of my request condescending.

**Comment by jezdez** [comment]
Talking about feelings is not simple, I guess it can feel like being in couples' therapy. I'm glad you're coming to terms of the impact a request like this has on the person it's directed at. Although I'm not sure if your apology is sincere I commend you for trying.

It probably stems from your assumption that I need to cater to the expectations to deliver to the community whenever it demands. But that's simply not the case - it's my sole decision to work in my free time, there is no contract, not even a code of honor in my experience. If your experience is different than I'm happy to hear. But from the stories of countless other maintainers I know my perspective isn't a unique one. The community takes often, but gives back rarely.

As with regard to the thickness of my skin, I beg your pardon? You got some balls to tell me I'm overreacting. I don't think you realize that you're blaming me for you using my free software. So maybe I'm wasting my time trying to explain it. But it's quite simple: It was your decision to use my software, not mine. I call bullshit about "community standards", especially if this is even a port of the [daemontools envdir](https://cr.yp.to/daemontools/envdir.html) -- a good alternative for you.

FWIW I don't care if anyone is "wasting time" using my software. The release on PyPI is a free and gratis offering to the community and not a promise to maintain it. It's even licensed with a very permissive license, so please feel to fork and maintain it yourself.

I'm gonna lock this issue now, just to make sure that our chat isn't disturbed by others.
